/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

(* top =  1  *)
(* src = "ternary_operator_mux.v:1.1-3.11" *)
module ternary_operator_mux(i0, i1, sel, y);
  (* src = "ternary_operator_mux.v:1.36-1.38" *)
  input i0;
  wire i0;
  (* src = "ternary_operator_mux.v:1.47-1.49" *)
  input i1;
  wire i1;
  (* src = "ternary_operator_mux.v:1.58-1.61" *)
  input sel;
  wire sel;
  (* src = "ternary_operator_mux.v:1.71-1.72" *)
  output y;
  wire y;
  assign y = sel ? (* src = "ternary_operator_mux.v:2.13-2.22" *) i1 : i0;
endmodule
