/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/sequence_detector.v:3.1-102.10" *)
module sequence_detector(clk, reset, din, detected);
  (* src = "rtl/sequence_detector.v:18.5-90.8" *)
  wire [2:0] _00_;
  (* src = "rtl/sequence_detector.v:18.5-90.8" *)
  wire [2:0] _01_;
  (* src = "rtl/sequence_detector.v:18.5-90.8" *)
  wire [2:0] _02_;
  (* src = "rtl/sequence_detector.v:18.5-90.8" *)
  wire [2:0] _03_;
  (* src = "rtl/sequence_detector.v:18.5-90.8" *)
  wire [2:0] _04_;
  (* src = "rtl/sequence_detector.v:18.5-90.8" *)
  wire [2:0] _05_;
  (* src = "rtl/sequence_detector.v:18.5-90.8" *)
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* src = "rtl/sequence_detector.v:4.17-4.20" *)
  input clk;
  wire clk;
  (* src = "rtl/sequence_detector.v:7.17-7.25" *)
  output detected;
  reg detected;
  (* src = "rtl/sequence_detector.v:6.17-6.20" *)
  input din;
  wire din;
  (* src = "rtl/sequence_detector.v:15.23-15.33" *)
  wire [2:0] next_state;
  (* src = "rtl/sequence_detector.v:5.17-5.22" *)
  input reset;
  wire reset;
  (* src = "rtl/sequence_detector.v:14.23-14.28" *)
  reg [2:0] state;
  (* src = "rtl/sequence_detector.v:92.5-100.8" *)
  always @(posedge clk)
    if (reset) state <= 3'h0;
    else state <= next_state;
  (* src = "rtl/sequence_detector.v:92.5-100.8" *)
  always @(posedge clk)
    if (_07_) detected <= 1'h0;
    else detected <= _06_;
  assign _09_ = ~ _12_;
  assign _07_ = | { _09_, reset };
  assign _08_ = | { _12_, _11_ };
  assign _01_ = din ? (* full_case = 32'd1 *) (* src = "rtl/sequence_detector.v:32.21-32.32|rtl/sequence_detector.v:32.17-38.20" *) 3'h1 : 3'h2;
  function [2:0] _23_;
    input [2:0] a;
    input [17:0] b;
    input [5:0] s;
    (* full_case = 32'd1 *)
    (* src = "rtl/sequence_detector.v:0.0-0.0|rtl/sequence_detector.v:21.9-89.16" *)
    (* parallel_case *)
    casez (s)
      6'b?????1:
        _23_ = b[2:0];
      6'b????1?:
        _23_ = b[5:3];
      6'b???1??:
        _23_ = b[8:6];
      6'b??1???:
        _23_ = b[11:9];
      6'b?1????:
        _23_ = b[14:12];
      6'b1?????:
        _23_ = b[17:15];
      default:
        _23_ = a;
    endcase
  endfunction
  assign next_state = _23_(3'h0, { _01_, _02_, _03_, _04_, _05_, _00_ }, { _10_, _16_, _15_, _14_, _13_, _08_ });
  assign _12_ = state == (* full_case = 32'd1 *) (* src = "rtl/sequence_detector.v:0.0-0.0|rtl/sequence_detector.v:21.9-89.16" *) 3'h6;
  assign _13_ = state == (* full_case = 32'd1 *) (* src = "rtl/sequence_detector.v:0.0-0.0|rtl/sequence_detector.v:21.9-89.16" *) 3'h5;
  assign _14_ = state == (* full_case = 32'd1 *) (* src = "rtl/sequence_detector.v:0.0-0.0|rtl/sequence_detector.v:21.9-89.16" *) 3'h4;
  assign _15_ = state == (* full_case = 32'd1 *) (* src = "rtl/sequence_detector.v:0.0-0.0|rtl/sequence_detector.v:21.9-89.16" *) 3'h3;
  assign _16_ = state == (* full_case = 32'd1 *) (* src = "rtl/sequence_detector.v:0.0-0.0|rtl/sequence_detector.v:21.9-89.16" *) 3'h2;
  assign _10_ = state == (* full_case = 32'd1 *) (* src = "rtl/sequence_detector.v:0.0-0.0|rtl/sequence_detector.v:21.9-89.16" *) 3'h1;
  assign _11_ = ! (* full_case = 32'd1 *) (* src = "rtl/sequence_detector.v:0.0-0.0|rtl/sequence_detector.v:21.9-89.16" *) state;
  assign _06_ = din ? (* full_case = 32'd1 *) (* src = "rtl/sequence_detector.v:77.21-77.32|rtl/sequence_detector.v:77.17-83.20" *) 1'h1 : 1'h0;
  assign _00_ = din ? (* full_case = 32'd1 *) (* src = "rtl/sequence_detector.v:77.21-77.32|rtl/sequence_detector.v:77.17-83.20" *) 3'h1 : 3'h0;
  assign _05_ = din ? (* full_case = 32'd1 *) (* src = "rtl/sequence_detector.v:68.21-68.32|rtl/sequence_detector.v:68.17-74.20" *) 3'h3 : 3'h6;
  assign _04_ = din ? (* full_case = 32'd1 *) (* src = "rtl/sequence_detector.v:59.21-59.32|rtl/sequence_detector.v:59.17-65.20" *) 3'h1 : 3'h5;
  assign _03_ = din ? (* full_case = 32'd1 *) (* src = "rtl/sequence_detector.v:50.21-50.32|rtl/sequence_detector.v:50.17-56.20" *) 3'h4 : 3'h2;
  assign _02_ = din ? (* full_case = 32'd1 *) (* src = "rtl/sequence_detector.v:41.21-41.32|rtl/sequence_detector.v:41.17-47.20" *) 3'h3 : 3'h0;
endmodule
